#!/usr/bin/env bash

set -eu

tmpdir="$(mktemp -d)"

test -f "${1:-}" || {
  echo "markatzea <file>" >&2
  exit 1
}

csplit -s \
  --prefix="$tmpdir/$1." --suffix-format='%03d.part' \
  "$1" '/^```/' {*}

ls "$tmpdir/$1".*.part | while read -r file; do
  read -r lang comm < "$file"

  IFS='# ' read -r _ script_alias < "$file"

  # echo "goody-bag: $baba"

  [[ $lang != \`\`\`* ]] || [[ -z "$comm" ]] || {
    # echo "info: $comm" >&2
    printf '> `%s`\n\n' "$comm"
    cat "$file"
    echo '```'
    echo '```' # output
    # TODO: do not write output codeblock when empty.
    tail -n +2 "$file" | eval "$comm" || {
      ec="$?"
      {
        printf "error: The following script exited with exit code %s.\n" "$ec"
        cat "$file"
        echo '```'
        echo 'Use "<interpreter> || true" to allow failure.\n'
      } >&2
      exit "$ec"
    }

    continue
  }

  cat "$file"
done

rm -r "$tmpdir"
