#!/usr/bin/env perl

use strict;
use warnings;
use autodie;

my $tmp_dir="/tmp/memplate";

-e "$tmp_dir" or mkdir $tmp_dir;

if (exists($ENV{'SCOPE'})) {
  -e "$tmp_dir/$ENV{'SCOPE'}" or mkdir "$tmp_dir/$ENV{'SCOPE'}";
}

sub alias_file_path {
  my ($alias) = @_;

  if (exists($ENV{'SCOPE'})) {
    return "$tmp_dir/$ENV{'SCOPE'}/$alias";
  }

  return "/$tmp_dir/$alias";
}

if ($ARGV[0]) {
  open my $fh, '>', alias_file_path($ARGV[0]);
  print $fh <STDIN>;
  exit;
}

sub weave {
  my ($prepend, $fh) = @_;

  while (my $line = <$fh>) {
    chomp($line);

    my @spl = split(/\</, $line);

    if (exists($spl[1])) {
      open my $fhn, '<', alias_file_path($spl[1]);
      weave($prepend . $spl[0], $fhn);
      next;
    }

    print $prepend . $line . "\n";
  }

  close $fh;
}

weave("", \*STDIN);
